version: "3.8"

services:
    app:
        build: .
        ports:
            - "5000:5000"
        environment:
            - PORT=5000
        depends_on:
            - postgres
            - redis

    postgres:
        image: postgres:13
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=booktrading
        # volumes:
            # - ./pgdata:/var/lib/postgresql/data
            # - ./src/migrations:/docker-entrypoint-initdb.d
    redis:
        image: redis:6
